#!/bin/bash
# map-ecosystem.sh — Generate dependency graph for the SuperInstance ecosystem
# Reads pyproject.toml, Cargo.toml, and package.json files to build a Mermaid graph

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$SCRIPT_DIR/docs/DEPENDENCY-GRAPH.md"

echo "# Ecosystem Dependency Graph" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```mermaid' >> "$OUTPUT"
echo "graph TD" >> "$OUTPUT"

cd "$SCRIPT_DIR"

# Python packages
for f in */pyproject.toml; do
  if [ ! -f "$f" ]; then continue; fi
  pkg=$(grep '^name = ' "$f" | head -1 | sed 's/.*= "\(.*\)"/\1/')
  if [ -z "$pkg" ]; then continue; fi
  echo "  ${pkg//-/_}[${pkg}]" >> "$OUTPUT"
done

# Rust packages
for f in */Cargo.toml; do
  if [ ! -f "$f" ]; then continue; fi
  pkg=$(grep '^name = ' "$f" | head -1 | sed 's/.*= "\(.*\)"/\1/')
  if [ -z "$pkg" ]; then continue; fi
  echo "  ${pkg//-/_}[${pkg}]" >> "$OUTPUT"
done

echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated by map-ecosystem.sh on $(date)" >> "$OUTPUT"

echo "Written to $OUTPUT ($(wc -l < "$OUTPUT") lines)"